default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "stage" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "stage" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stage_development

test:
  <<: *default
  database: stage_test

production:
  primary:
    <<: *default
    database: stage_production
  cache:
    <<: *default
    database: stage_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: stage_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: stage_production_cable
    migrations_paths: db/cable_migrate
